name: check warnings - gfortran

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  FC: gfortran

jobs:
  check_warnings:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            cache-downloads: true
            cache-env: true

      - name: Install gfortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Print python package versions
        run: |
          pip list

      - name: Setup modflow
        run: |
          meson setup builddir -Ddebug=false -Dwerror=true

      - name: Build modflow and check for warnings
        run: |
          meson compile -C builddir

  test_night_build_script:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            cache-downloads: true
            cache-env: true

      - name: Install gfortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Print python package versions
        run: |
          pip list

      - name: Update flopy MODFLOW 6 classes
        working-directory: autotest
        run: |
          python update_flopy.py

      - name: Run nightly build script
        working-directory: distribution
        run: |
          pytest -v -s build_nightly.py

      - name: Move the build zip file
        run: |
          ls -l ./distribution/*
          mv ./distribution/temp_zip/linux.zip ./linux.zip
          ls -l ./
