name: fortran-format-check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  fortan-format-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

      - name: Setup symbolic links on Linux
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Print python package versions
        run: |
          micromamba list

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Fortran source format check
        run: |
          .github/common/fortran-format-check.sh
