name: gfortran - previous versions

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        GCC_V: [5, 6, 7, 8]
    defaults:
      run:
        shell: bash

    if: github.repository_owner == 'MODFLOW-USGS'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.5
      with:
        auto-update-conda: true

    - name: Set up gfortran ${{ matrix.GCC_V }}
      run: |
        sudo apt-get install -y --no-install-recommends gcc-${{ matrix.GCC_V }} g++-${{ matrix.GCC_V }} gfortran-${{ matrix.GCC_V }}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.GCC_V }} 100 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.GCC_V }} \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.GCC_V }} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.GCC_V }}

    - name: Print GNU compiler versions
      run: |
        gcc --version
        gfortran --version
        g++ --version
        gcov --version

    - name: Install python packages
      run: |
        .github/common/install-python.sh

    - name: Print conda version
      run: |
        conda --version

    - name: Print python package versions
      run: |
        .github/common/python-version.sh

    - name: Set and print branch name
      run: |
        .github/common/git-branch-export.sh

    - name: Get regression test files
      run: |
        .github/common/get-regression-files.sh

    - name: Check out the correct regression test branch
      run: |
        .github/common/checkout-regression-branch.sh

    - name: Update flopy MODFLOW 6 classes
      run: |
        .github/common/update-flopy.sh

    - name: Build applications
      run: |
        nosetests -v --with-id --with-timer -w ./autotest get_build_exes.py

    - name: Test applications
      run: |
        nosetests -v --with-id --with-timer -w ./autotest
