# Parts of configuration file are based on the examples in this repository:
# https://github.com/oneapi-src/oneapi-ci
#
# Which have the following copyright:
# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT


## add this back in to on: if there is a need to debug the large tests
#
#pull_request:
#  branches:
#    - develop


name: Run and test modflow6-largetestmodels and modflow6-examples (z03)

on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        FC: [ ifort, gfortran ]
        test_script: [ largetests, examples ]
    defaults:
      run:
        shell: bash -l {0}

    if: github.repository_owner == 'MODFLOW-USGS'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            cache-downloads: true
            cache-env: true

      - name: set FC=ifort environmental variable
        if: matrix.FC == 'ifort'
        run: |
          echo "FC=ifort" >> $GITHUB_ENV

      - name: Install ifort
        if: matrix.FC == 'ifort'
        uses: modflowpy/install-intelfortran-action@v1

      - name: Install gfortran
        if: matrix.FC == 'gfortran'
        uses: modflowpy/install-gfortran-action@v1

      - name: Install additional python packages
        run: |
          micromamba install jupyter jupytext shapely scipy pandas pyshp

      - name: Print python package versions
        run: |
          pip list

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Get the appropriate large or example regression test files
        run: |
          .github/common/get-${{ matrix.test_script }}-regression-files.sh

      - name: Update flopy MODFLOW 6 classes
        run: |
          .github/common/update-flopy.sh

      - name: Run script to build example scripts
        if: matrix.test_script == 'examples'
        run: |
          cd ../modflow6-examples/etc/
          python ci_build_files.py
          ls -lh ../examples/
          cd ../../modflow6

      - name: activate ifort and build applications
        if: matrix.FC == 'ifort'
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          cd autotest
          pytest -v --durations=0 get_exes.py

      - name: Build gfortran applications
        if: matrix.FC == 'gfortran'
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          cd autotest
          pytest -v --durations=0 get_exes.py

      - name: Test applications
        working-directory: autotest
        run: |
          pytest -v -n=auto --durations=0 test_z03_${{ matrix.test_script }}.py