name: Pull Request Docs Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  rtd_build:
    runs-on: ubuntu-latest
    env:
      working-directory: .build_rtd_docs

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip and install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{env.working-directory}}

      - name: run sphinx
        run: |
          make html
        working-directory: ${{env.working-directory}}

      # Create an artifact of the processed files.
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: rtd-files-for-${{ github.sha }}
          path: |
            ${{env.working-directory}}/mf6io.rst
            ${{env.working-directory}}/_mf6io/
            ${{env.working-directory}}/_static/

  # trigger rtd if "rtd_build" job was successful
  rtd_trigger:
    name: rtd-trigger
    needs: rtd_build
    runs-on: ubuntu-latest

    if: github.repository_owner == 'MODFLOW-USGS' && github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Trigger RTDs build on push to repo branches
        uses: dfm/rtds-action@v1.0.3
        with:
          webhook_url: ${{ secrets.MF6_RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.MF6_RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}

  doxygen_build:
    runs-on: ubuntu-latest
    env:
      working-directory: .build_rtd_docs
      branch-name: ${GITHUB_REF##*/}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Print branch name
        run: |
          echo ${{env.branch-name}}

      - name: Install doxygen and graphviz
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz

      - name: run doxygen
        run: |
          doxygen
        working-directory: ${{env.working-directory}}

      - name: Deploy doxygen html to gh-pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.repository_owner == 'MODFLOW-USGS' && ${{env.branch-name}} == 'develop' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.working-directory}}/html