name: tests - gfortran - latest version

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  FC: gfortran

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            cache-downloads: true
            cache-env: true

      - name: Print python package versions
        run: |
          pip list

      - name: Install gfortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Test make for MODFLOW 6 programs
        working-directory: ./distribution
        run: |
          pytest -v -n=auto build_makefiles.py

      - name: Get regression test files
        run: |
          .github/common/get-regression-files.sh

      - name: Check out the correct regression test branch
        run: |
          .github/common/checkout-regression-branch.sh

      - name: Update flopy MODFLOW 6 classes
        run: |
          .github/common/update-flopy.sh

      - name: Setup modflow
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin

      - name: Build and install modflow
        run: |
          meson install -C builddir

      - name: Get executables
        working-directory: autotest
        run: |
          pytest -v --durations=0 get_exes.py

      - name: Test applications
        working-directory: autotest
        run: |
          pytest -v -n=auto --durations=0
