name: tests - gfortran - latest version

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  FC: gfortran

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9

      - name: Workaround for windows-2022 v20220626.1 gfortran executable run failures
        if: runner.os == 'Windows'
        run: |
          .github/common/link-gfortranlib5.sh

      - name: Setup symbolic links on Linux
        if: runner.os == 'Linux'
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Setup symbolic link to gfortran on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          sudo ln -fs /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo ln -fs /usr/local/bin/gcc-11 /usr/local/bin/gcc
          sudo ln -fs /usr/local/bin/g++-11 /usr/local/bin/g++

      - name: Print GNU compiler versions
        run: |
          gfortran --version
          gcc --version
          g++ --version

      - name: Install python packages
        run: |
          .github/common/install-python-std.sh

      - name: Print python package versions
        run: |
          pip list

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Test make for MODFLOW 6 programs
        working-directory: ./distribution
        run: |
          pytest -v -n=auto build_makefiles.py

      - name: Get regression test files
        run: |
          .github/common/get-regression-files.sh

      - name: Check out the correct regression test branch
        run: |
          .github/common/checkout-regression-branch.sh

      - name: Update flopy MODFLOW 6 classes
        run: |
          .github/common/update-flopy.sh

      - name: Setup modflow
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin

      - name: Build and install modflow
        run: |
          meson install -C builddir

      - name: Get executables
        working-directory: autotest
        run: |
          pytest -v --durations=0 get_exes.py

      - name: Test applications
        working-directory: autotest
        run: |
          pytest -v -n=auto --durations=0
