name: tests - gfortran - end of life versions

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  FC: gfortran

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        GCC_V: [ 5, 6 ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

      - name: Set up gfortran ${{ matrix.GCC_V }}
        run: |
          sudo apt-get install -y --no-install-recommends gcc-${{ matrix.GCC_V }} g++-${{ matrix.GCC_V }} gfortran-${{ matrix.GCC_V }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.GCC_V }} 100 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.GCC_V }} \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.GCC_V }} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.GCC_V }}

      - name: Print GNU compiler versions
        run: |
          gcc --version
          gfortran --version
          g++ --version
          gcov --version

      - name: Print python package versions
        run: |
          micromamba list

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Get regression test files
        run: |
          .github/common/get-regression-files.sh

      - name: Check out the correct regression test branch
        run: |
          .github/common/checkout-regression-branch.sh

      - name: Update flopy MODFLOW 6 classes
        run: |
          .github/common/update-flopy.sh

      - name: Setup modflow
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin

      - name: Build and install modflow
        run: |
          meson install -C builddir

      - name: Get executables
        working-directory: autotest
        run: |
          pytest -v --durations=0 get_exes.py

      - name: Test applications
        working-directory: autotest
        run: |
          pytest -v -n=auto --durations=0
